import subprocess
import os
import pathlib
import yaml
import argparse
from typing import List, Dict, Any, Optional

"""
PARAMETERS EXPLAINED:
====================

n (Number of Items):
-------------------
- The total number of items available for the knapsack

r (Range of Coefficients):
-------------------------  
- Maximum value for randomly generated weights and profits
- All item weights will be in range [1, r]
- All item profits will be in range [1, r] (for uncorrelated type)

type (Instance Type):
--------------------
Controls the correlation between item weights and profits. This is CRUCIAL for 
testing different aspects of knapsack algorithms:

Type 1 - UNCORRELATED:
  * weight[i] = random(1, r)
  * profit[i] = random(1, r)  
  * No relationship between weight and profit
  * Most general case, tests basic algorithm performance

Type 2 - WEAKLY CORRELATED:
  * weight[i] = random(1, r)
  * profit[i] = random(weight[i] - r/10, weight[i] + r/10)
  * Profit loosely follows weight (with noise)
  * More realistic - expensive items tend to be heavier

Type 3 - STRONGLY CORRELATED:
  * weight[i] = random(1, r)
  * profit[i] = weight[i] + 10
  * Profit directly proportional to weight
  * Tests algorithms when profit/weight ratio is nearly constant
  * Can reveal weaknesses in greedy approaches

Type 4 - SUBSET SUM:
  * weight[i] = random(1, r)
  * profit[i] = weight[i] (exactly equal)
  * Special case where we're just trying to fill capacity exactly
  * Tests pure combinatorial optimization

i (Instance Number/Seed):
------------------------
- Used as the random seed for generating this specific instance
- Same (n, r, type, i, S) will ALWAYS generate identical instances
- Allows reproducible experiments
- Typical values: 1, 2, 3, ..., up to however many instances you want
- Examples:
  * i=1: first instance with this configuration
  * i=42: 42nd instance (different random items, same parameters)


S (Series Size - CAPACITY CONTROLLER):
=====================================
CAPACITY FORMULA: capacity = (i × total_weight) / (S + 1)

Where total_weight = sum of all item weights

DIFFICULTY LEVELS:
-----------------
S = 100:     VERY EASY   (~50-90% of total weight fits)
S = 1000:    EASY        (~10-50% of total weight fits)  
S = 10000:   MEDIUM      (~1-10% of total weight fits)
S = 100000:  HARD        (~0.1-1% of total weight fits)
S = 1000000: VERY HARD   (~0.01-0.1% of total weight fits)
"""

class YAMLGenerator:
    """
    A class to generate knapsack instances using a generator and convert them to YAML format.
    """
    
    def __init__(self, generator_path: str = "generator.exe"):
        """
        Initialize the generator.
        
        Args:
            generator_path: Path to the Pisinger generator executable
        """
        self.generator_path = generator_path
        self.type_names = {
            1: "uncorrelated",
            2: "weakly_correlated", 
            3: "strongly_correlated",
            4: "subset_sum"
        }
        self._validate_generator()
    
    def _validate_generator(self) -> None:
        """Validate that the generator executable exists."""
        if not os.path.exists(self.generator_path):
            raise FileNotFoundError(f"Generator not found at: {self.generator_path}")
    
    def run_generator(self, n: int, r: int, type_: int, i: int, S: int) -> bool:
        """
        Run the C generator program with given parameters.
        
        Args:
            n: number of items
            r: range of coefficients
            type_: instance type (1-4)
            i: instance number (seed)
            S: series size
        
        Returns:
            True if successful, False otherwise
        """
        try:
            result = subprocess.run([
                self.generator_path, str(n), str(r), str(type_), str(i), str(S)
            ], capture_output=True, text=True, check=True)
            return True
        except subprocess.CalledProcessError as e:
            print(f"Error running generator: {e}")
            print(f"stdout: {e.stdout}")
            print(f"stderr: {e.stderr}")
            return False
        except FileNotFoundError:
            print(f"Generator not found at: {self.generator_path}")
            return False
    
    def parse_test_file(self, filename: str = "test.in") -> Dict[str, Any]:
        """
        Parse the test.in file generated by the C program.
        
        Args:
            filename: path to the test file
        
        Returns:
            Dictionary with parsed data
        """
        if not os.path.exists(filename):
            raise FileNotFoundError(f"Test file {filename} not found")
        
        try:
            with open(filename, 'r') as f:
                lines = f.readlines()
            
            # Parse number of items
            num_items = int(lines[0].strip())
            
            # Parse items
            items = []
            for i in range(1, num_items + 1):
                parts = lines[i].strip().split()
                if len(parts) < 3:
                    raise ValueError(f"Invalid item format in line {i+1}")
                
                item_id = int(parts[0])
                profit = int(parts[1])
                weight = int(parts[2])
                items.append({"weight": weight, "value": profit})
            
            # Parse capacity
            capacity = int(lines[num_items + 1].strip())
            return {
                "num_items": num_items,
                "items": items,
                "capacity": capacity
            }
        
        except (ValueError, IndexError) as e:
            raise ValueError(f"Error parsing test file: {e}")
    
    def get_type_name(self, type_num: int) -> str:
        """Convert type number to descriptive name."""
        return self.type_names.get(type_num, f"type_{type_num}")
    
    def create_yaml_instance(self, parsed_data: Dict[str, Any], experiment_name: str, 
                            random_seed: int, notes: str = "") -> Dict[str, Any]:
        """
        Convert parsed data to YAML format.
        
        Args:
            parsed_data: data from parse_test_file
            experiment_name: name for the experiment
            random_seed: random seed used
            notes: additional notes
        
        Returns:
            Dictionary in the target YAML format
        """
        return {
            "experiment_name": experiment_name,
            "random_seed": random_seed,
            "notes": notes,
            "number_knapsack": 1,
            "capacity": parsed_data["capacity"],
            "items": parsed_data["items"]
        }
    
    def generate_single_instance(self, n: int, r: int, type_: int, i: int, S: int,
                                experiment_name: Optional[str] = None,
                                notes: Optional[str] = None) -> Optional[Dict[str, Any]]:
        """
        Generate a single knapsack instance.
        
        Args:
            n: number of items
            r: range of coefficients  
            type_: instance type (1-4)
            i: instance number (seed)
            S: series size
            experiment_name: custom experiment name (auto-generated if None)
            notes: custom notes (auto-generated if None
        """
        # Run the C generator
        if not self.run_generator(n, r, type_, i, S):
            return None
        
        try:
            # Parse the generated file
            parsed_data = self.parse_test_file("test.in")
            
            # Create experiment name if not provided
            if experiment_name is None:
                type_name = self.get_type_name(type_)
                experiment_name = f"Pisinger_{type_name}_n{n}_r{r}_S{S}_i{i}"
            
            # Create notes if not provided
            if notes is None:
                type_name = self.get_type_name(type_)
                notes = f"Generated using Pisinger's generator. Type: {type_name}, Items: {n}, Range: {r}, Series: {S}, Instance: {i}"
            
            # Convert to YAML format
            yaml_data = self.create_yaml_instance(
                parsed_data, 
                experiment_name, 
                random_seed=i,
                notes=notes
            )
            
            return yaml_data
            
        except Exception as e:
            print(f"Error processing instance: {e}")
            return None
    
    def save_yaml_instance(self, yaml_data: Dict[str, Any], output_path: str) -> bool:
        try:
            # Create directory if it doesn't exist
            os.makedirs(os.path.dirname(output_path), exist_ok=True)
            
            # Build YAML content as list of lines
            doc_lines = [
                f'experiment_name: "{yaml_data["experiment_name"]}"',
                f'random_seed: {yaml_data["random_seed"]}',
                f'notes: "{yaml_data["notes"]}"',
                f'number_knapsack: {yaml_data["number_knapsack"]}',
                f'capacity: {yaml_data["capacity"]}',
                "items:"
            ]
            
            # Add items in compact format
            for item in yaml_data["items"]:
                doc_lines.append(f"- {{weight: {item['weight']}, value: {item['value']}}}")
            
            # Write to file
            with open(output_path, 'w') as f:
                f.write("\n".join(doc_lines) + "\n")
                
            return True
        except Exception as e:
            print(f"Error saving YAML file {output_path}: {e}")
            return False
    
    def generate_multiple_instances(self, n: int, r: int, type_: int, S: int, 
                                   num_instances: int, output_dir: str = "instances",
                                   custom_name_prefix: Optional[str] = None, i_start: int = 1) -> Dict[str, Any]:
        """
        Generate multiple knapsack instances and save them as YAML files.
        
        Args:
            n: number of items
            r: range of coefficients  
            type_: instance type (1-4)
            S: series size
            num_instances: how many instances to generate
            output_dir: directory to save YAML files
            custom_name_prefix: custom prefix for filenames
        
        Returns:
            Dictionary with generation statistics
        """
        # Create output directory if it doesn't exist
        os.makedirs(output_dir, exist_ok=True)
        
        type_name = self.get_type_name(type_)
        successful_generations = 0
        failed_generations = 0
        skipped_generations = 0
        generated_files = []
        max_attempts = 100
        
        print(f"Generating {num_instances} instances...")
        print(f"Parameters: n={n}, r={r}, type={type_} ({type_name}), S={S}")
        print("-" * 50)
        i = i_start
        while successful_generations < num_instances and (successful_generations + failed_generations + skipped_generations) < max_attempts:
            
            print(f"Generating instance {i}/{num_instances}...", end=" ")
            
            # Generate single instance
            yaml_data = self.generate_single_instance(n, r, type_, i, S)
            total_weight = sum(item["weight"] for item in yaml_data["items"])
            if total_weight <= yaml_data["capacity"] or yaml_data["capacity"] == r+1:
                if total_weight == yaml_data["capacity"]:
                    print(f"SKIPPED (total_weight {total_weight} == capacity {yaml_data['capacity']})")
                else:
                    print(f"capacity cap in C code")
                skipped_generations += 1
                i += 1
                continue
            if yaml_data is None:
                print("FAILED")
                failed_generations += 1
                i += 1
                continue
            
            # Create filename
            if custom_name_prefix:
                filename = f"{custom_name_prefix}_i{i}.yaml"
            else:
                filename = f"n{n}_r{r}_S{S}_i{i}_{type_name}.yaml"
            
            output_path = os.path.join(output_dir, filename)
            
            # Save to file
            if self.save_yaml_instance(yaml_data, output_path):
                successful_generations += 1
                generated_files.append(output_path)
                print(f"SUCCESS -> {filename}")
            else:
                failed_generations += 1
                print(f"FAILED - Could not save file")
            i += 1
        
        print("-" * 50)
        print(f"Successfully generated {successful_generations}/{num_instances} instances")
        print(f"Files saved in: {output_dir}/")
        
        # Clean up the temporary test.in file
        if os.path.exists("test.in"):
            os.remove("test.in")
        
        return {
            "successful": successful_generations,
            "failed": failed_generations,
            "total": num_instances,
            "output_dir": output_dir,
            "generated_files": generated_files,
            "parameters": {
                "n": n, "r": r, "type": type_, "S": S
            }
        }
    
    def generate_batch_instances(self, configurations: List[Dict[str, Any]], 
                                output_dir: str = "batch_instances") -> Dict[str, Any]:
        """
        Generate instances for multiple configurations.
        
        Args:
            configurations: List of configuration dictionaries with keys:
                           n, r, type, S, count, (optional: name_prefix)
            output_dir: base output directory
        
        Returns:
            Dictionary with batch generation statistics
        
        Example:
            configs = [
                {"n": 20, "r": 1000, "type": 1, "S": 1000, "count": 5},
                {"n": 50, "r": 500, "type": 2, "S": 1000, "count": 3, "name_prefix": "custom"}
            ]
        """
        total_successful = 0
        total_failed = 0
        all_generated_files = []
        results = []
        
        print(f"Starting batch generation with {len(configurations)} configurations...")
        print("=" * 60)
        
        for idx, config in enumerate(configurations, 1):
            print(f"\nConfiguration {idx}/{len(configurations)}:")
            
            # Extract parameters
            n = config["n"]
            r = config["r"]
            type_ = config["type"]
            S = config["S"]
            count = config["count"]
            i_start = config.get("i_start")
            name_prefix = config.get("name_prefix")
            
            # Create subdirectory for this configuration
            type_name = self.get_type_name(type_)
            sub_dir = os.path.join(output_dir)
            
            # Generate instances for this configuration
            result = self.generate_multiple_instances(
                n=n, r=r, type_=type_, S=S, 
                num_instances=count, 
                output_dir=sub_dir,
                custom_name_prefix=name_prefix, i_start=i_start
            )
            
            total_successful += result["successful"]
            total_failed += result["failed"]
            all_generated_files.extend(result["generated_files"])
            results.append(result)
        
        print("=" * 60)
        print(f"Batch generation complete!")
        print(f"Total successful: {total_successful}")
        print(f"Total failed: {total_failed}")
        print(f"Files saved in: {output_dir}/")
        
        return {
            "total_successful": total_successful,
            "total_failed": total_failed,
            "configurations_processed": len(configurations),
            "output_dir": output_dir,
            "all_generated_files": all_generated_files,
            "individual_results": results
        }

def main():
    parser = argparse.ArgumentParser(
        description="Generate knapsack instances using Pisinger's generator and convert to YAML",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    
    parser.add_argument("-n", "--items", type=int, required=True,
                       help="Number of items")
    parser.add_argument("-r", "--range", type=int, required=True,
                       help="Range of coefficients (max weight/profit)")
    parser.add_argument("-t", "--type", type=int, choices=[1,2,3,4], required=True,
                       help="Instance type: 1=uncorr, 2=weakly corr, 3=strongly corr, 4=subset sum")
    parser.add_argument("-S", "--series", type=int, required=True,
                       help="Series size (affects capacity calculation)")
    parser.add_argument("--count", type=int, default=5,
                       help="Number of instances to generate (default: 5)")
    parser.add_argument("-o", "--output", type=str, default="instances",
                       help="Output directory (default: instances)")
    parser.add_argument("--generator", type=str, default="generator.exe",
                       help="Path to generator executable (default: generator.exe)")
    parser.add_argument("--prefix", type=str, default=None,
                       help="Custom filename prefix")
    
    args = parser.parse_args()
    
    try:
        # Create generator instance
        generator = YAMLGenerator(generator_path=args.generator)
        
        # Generate instances
        result = generator.generate_multiple_instances(
            n=args.items,
            r=args.range, 
            type_=args.type,
            S=args.series,
            num_instances=args.count,
            output_dir=args.output,
            custom_name_prefix=args.prefix
        )
        
        print(f"\nFinal Summary:")
        print(f"Success rate: {result['successful']}/{result['total']} ({100*result['successful']/result['total']:.1f}%)")
        
    except Exception as e:
        print(f"Error: {e}")


def create_instances_set_size():

    generator = YAMLGenerator(str(pathlib.Path(__file__).resolve().parent / "generator.exe"))
    configurations = []
    """configurations += [{"n": 25, "r": 300, "type": 2, "S": S, "count": 50, "i_start": 8} for S in range(4, 500, 5)]"""
    configurations = [
        {"n": 10, "r": 400, "type": 3, "S": 50, "count": 100, "i_start": 10},
        {"n": 11, "r": 400, "type": 3, "S": 51, "count": 100, "i_start": 10},
        {"n": 12, "r": 400, "type": 3, "S": 52, "count": 100, "i_start": 10},
        {"n": 13, "r": 400, "type": 3, "S": 53, "count": 100, "i_start": 10},
        {"n": 14, "r": 400, "type": 3, "S": 55, "count": 100, "i_start": 10},
        {"n": 15, "r": 400, "type": 3, "S": 28, "count": 100, "i_start": 10},
        {"n": 16, "r": 400, "type": 3, "S": 41, "count": 100, "i_start": 10},
        {"n": 17, "r": 400, "type": 3, "S": 21, "count": 100, "i_start": 10},
        {"n": 18, "r": 400, "type": 3, "S": 87, "count": 100, "i_start": 10},
        {"n": 19, "r": 400, "type": 3, "S": 54, "count": 100, "i_start": 10},
        {"n": 20, "r": 400, "type": 3, "S": 82, "count": 100, "i_start": 10},
        {"n": 21, "r": 400, "type": 3, "S": 50, "count": 100, "i_start": 10},
        {"n": 22, "r": 400, "type": 3, "S": 51, "count": 100, "i_start": 10},
        {"n": 23, "r": 400, "type": 3, "S": 52, "count": 100, "i_start": 10},
        {"n": 24, "r": 400, "type": 3, "S": 53, "count": 100, "i_start": 10},
        {"n": 24, "r": 400, "type": 3, "S": 55, "count": 100, "i_start": 10},
        {"n": 25, "r": 400, "type": 3, "S": 28, "count": 100, "i_start": 10},
        {"n": 26, "r": 400, "type": 3, "S": 41, "count": 100, "i_start": 10},
        {"n": 27, "r": 400, "type": 3, "S": 21, "count": 100, "i_start": 10},
        {"n": 28, "r": 400, "type": 3, "S": 87, "count": 100, "i_start": 10},
        {"n": 29, "r": 400, "type": 3, "S": 54, "count": 100, "i_start": 10},
        {"n": 30, "r": 400, "type": 3, "S": 82, "count": 100, "i_start": 10},
    ]
    
    batch_result = generator.generate_batch_instances(
        configurations, output_dir="config\\Debug_bias_strong_10_30\\"
    )
    print(f"Batch generated {batch_result['total_successful']} instances")
    
    """
    On average we need to fulfill:
    i*n > 2S AND S+1 > i
    to have a valid capacity and no duplicates. 
    """
    for item in configurations:
        if item["i_start"]*item["n"]*(item["r"] + 1) <= 2*item["S"]*item["r"]:
            print("Warning: i*n <= 2S may lead to duplicates where c=r+1")
        if item["S"] + 1 <= item["i_start"]:
            print("Warning: S+1 <= i may lead to trivial instances.")
    

if __name__ == "__main__":
    create_instances_set_size()